server:
  host: "0.0.0.0"
  port: 8086

model:
  quality:
    onnx_path: "src/models/saved_models/quality_predict.onnx"
    version: "1.0.0"
  production:
    onnx_path: "src/models/saved_models/output_predict.onnx"
    version: "1.0.0"

llm:
  api_key: "4a91b805b02e4693bc57b8d40292e595.bTm1SBzfsWvWMRXo"
  model: "glm-4-flash"

kafka:
  bootstrap_servers: "localhost:9092"
  group_id: "ai-service-group"
  topics:
    - "mes-device-data"

redis:
  host: "localhost"
  port: 6379
  db: 1

feature:
  sliding_window_size: 60
  aggregation_interval: 10
